version: '3.9'

services:
    firewall:
        restart: unless-stopped
        build: .
        ports:
            - 80:80
        environment:
            - NGINX_PORT=80
        volumes:
            - /execute/db
        