[package]
name = "nfqueue_regex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyperscan = "0.3.2"
nfqueue = "0.9.1"
libtins-rs = { git = "https://github.com/Pwnzer0tt1/libtins-rs.git" }
