name: Run Test on Docker Image

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and run firegex
      run: python3 start.py -b --psw-no-interactive testpassword
    - name: Run tests
      run: cd tests && ./run_tests.sh
      
